### ISSUE TITLE
Make POC to compile for Linux arm64 in macOS M1

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#232]
#### Description
To evaluate a quick solution to #92 implement a POC of compiling khiops in a docker in a mac ARM.

**Comment by bruno-at-orange** [comment]
POC done 
- Mac ARM + Docker Ubuntu 22.04 aarch64
Nothing to say for the deb packages

- Conda
With conda in docker on mac, there are few problems with versions: `mpich=4.0.3` and `gxx=12` are not available.
I used the following `conda_build_config.yaml`:
```yaml
mpi:
  - mpich=4.1.1 # [linux]
  - mpich=3.4.3 # [osx]
  - msmpi=10.1.1 # [win]
c_compiler:
  - gcc # [linux]
  - clang # [osx]
  - vs2022 # [win]
c_compiler_version:
  - 11 # [linux]
  - 16 # [osx]
cxx_compiler:
  - gxx # [linux]
  - clangxx # [osx]
  - vs2022 # [win]
cxx_compiler_version:
  - 11 # [linux]
  - 16 # [osx]
```
