### ISSUE TITLE
Run unit tests only when it is useful

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#50]
When I work on workflows, each time I push my work, unit tests are triggered. And I am 100% sure they will pass because I don't modify the sources or the cmake files.

I suggest to trigger the unit tests based on which files are involved in the push. Some documentation [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths)

For example:
```
on:
  push:
    paths:
      - '**.cpp'
      - '*.h'
      - '**/CMakeLists.txt'
```
